[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
hob_dao = "CX6oBVoDv3dFWsSmEJbaWAaNzdhyjbBDdCCue8vDmQSo"

[programs.devnet]
hob_dao = "CX6oBVoDv3dFWsSmEJbaWAaNzdhyjbBDdCCue8vDmQSo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/nizarsyahmi37/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
